parser: '@babel/eslint-parser'
plugins:
  - 'react'
  - 'jsx-a11y'
  # https://ja.reactjs.org/docs/hooks-rules.html#eslint-plugin
  - 'react-hooks'
  - 'prettier'
env:
  node: true
  browser: true
  es6: true
extends: './eslint.extends.yml'
