endOfLine: "lf"

printWidth: 100
tabWidth: 2
useTabs: false


overrides:
  - files: '*.scss'
    options:
      singleQuote: false
      parser: "scss"
  - files: '*.md'
    options:
      singleQuote: false
      parser: 'markdown'
  - files: '*.{js,jsx}'
    options:
      singleQuote: true
      trailingComma: "es5"
      parser: "flow"
