plugins:
  - "stylelint-scss"
  #  - "stylelint-order"
  - "stylelint-prettier"
extends:
  #  https://stylelint.io/migration-guide/to-14/
  - "stylelint-config-standard-scss"
  # https://github.com/stylelint/stylelint-config-standard/blob/master/index.js
  # https://github.com/prettier/stylelint-prettier#recommended-configuration
  - "stylelint-prettier/recommended"
  # https://github.com/stormwarning/stylelint-config-recess-order
  # https://github.com/twitter/recess/blob/29bccc870b7b4ccaa0a138e504caf608a6606b59/lib/lint/strict-property-order.js
  # https://github.com/twbs/bootstrap/blob/ba878eb542ab6c04786741569ba089d02e9bea46/.stylelintrc#L36
  - "stylelint-config-recess-order"
syntax: "scss"
ignoreFiles:
  - "**/*.js"
  - "src-scss/**/*.scss"
rules:

  prettier/prettier:
    - true
  indentation: 2
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: null
  # 「詳細度が低い順に書く」 - /scss/dependencies/_style.scss
  #  修正不可な場合はコメントにする
  no-descending-specificity: null
  # https://github.com/hudochenkov/stylelint-order#usage
#  order/order:
#    - custom-properties
#    - declarations
#  order/properties-alphabetical-order: true
  keyframes-name-pattern: null
  selector-class-pattern: null
  font-family-name-quotes: null
  number-max-precision: null
